- name: Install postfix
  ansible.builtin.apt:
    name: postfix

- name: Install postfix-pgsql
  ansible.builtin.apt:
    name: postfix-pgsql
  when: postfix.psql is defined

- name: Deploy postfix configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    etc/postfix/main.cf

- name: Deploy postfix postgresql configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/postfix/pgsql-aliases.cf
    - etc/postfix/pgsql-boxes.cf
  when: postfix.psql is defined

- name: Deploy letsencrypt hook
  ansible.builtin.template:
    src: etc/letsencrypt/hook/postfix.hook
    dest: /etc/letsencrypt/hook/postfix.hook
